
import java.io.IOException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karin
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.jsoup.nodes.Document;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.PDType1Font;
import org.jsoup.Jsoup;
public class OKNO extends javax.swing.JFrame {

    /**
     * Creates new form OKNO
     */
    public OKNO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("KLIKNIJ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("NIKE");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                       String[] columnNames = {"Nazwa", "Cena"};

        // Tworzenie modelu tabeli
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
    
    Document docAnswear;
    Document docRuncolors;
    String zapytanie = jTextField1.getText();
    try {
        // Dane z docAnswear
        docAnswear = Jsoup.connect("https://answear.com/k/ona?q=" + zapytanie).get();

        // Dane z docAnswear
        docRuncolors = Jsoup.connect("https://runcolors.pl/search.php?text=" + zapytanie).get();

        //wyciągniecie html z Answear
        //System.out.println("" + docAnswear.html());
        ///wyciągniecie html z Runcolors
        //System.out.println("" + docRuncolors.html());

        Elements productsAnswear = docAnswear.getElementsByClass("ProductItem__productCard__8ivfZ ProductItem__productCardExtraPadding__CI0Tn ProductItem__productCardHover__5l6PF");
        int iloscProduktowAnswear = productsAnswear.size();
        System.out.println("ILE ANSWEAR= " + iloscProduktowAnswear);

        for (Element product : productsAnswear) {
            Elements names = product.getElementsByClass("ProductItem__productCardName__DCKIH");
            Elements prize = product.getElementsByClass("ProductItemPrice__priceSaleMinimal__+YZVp");

            // sprawdzanie czy listy sa puste u answear
            if (!names.isEmpty() && !prize.isEmpty()) {
                System.out.println("NAZWA ANSWEAR= " + names.get(0).text());
                System.out.println("CENA ANSWEAR= " + prize.get(0).text());
            } else {
                System.out.println("Brak nazwy lub ceny dla produktu");
            }
        }

        Elements productsRuncolors = docRuncolors.getElementsByClass("product");
        int iloscProduktowRuncolors = productsRuncolors.size();
        System.out.println("ILE RUNCOLORS= " + iloscProduktowRuncolors);

        for (Element product : productsRuncolors) {
            Elements names = product.getElementsByClass("product__name");
            Elements prize = product.getElementsByClass("price");

            // sprawdzanie czy listy sa puste u runcolors
            if (!names.isEmpty() && !prize.isEmpty()) {
                System.out.println("NAZWA RUNCOLORS= " + names.get(0).text());
                System.out.println("CENA RUNCOLORS= " + prize.get(0).text());
            } else {
                System.out.println("Brak nazwy lub ceny dla produktu");
            }
        }
        //kto ma wiecej produktow?
            if (iloscProduktowAnswear > iloscProduktowRuncolors) {
                System.out.println("Answear ma więcej produktów niż Runcolors.");
            } else if (iloscProduktowAnswear < iloscProduktowRuncolors) {
                System.out.println("Runcolors ma więcej produktów niż Answear.");
            } else {
                System.out.println("Obie strony mają tę samą ilość produktów.");
            }
             
            
            //Jtable
        for (Element product : productsAnswear) {
            Elements names = product.getElementsByClass("ProductItem__productCardName__DCKIH");
            Elements prize = product.getElementsByClass("ProductItemPrice__priceSaleMinimal__+YZVp");

            if (!names.isEmpty() && !prize.isEmpty()) {
                // Dodawanie danych do modelu tabeli
                tableModel.addRow(new Object[]{names.get(0).text(), prize.get(0).text()});
            }
        }

        for (Element product : productsRuncolors) {
            Elements names = product.getElementsByClass("product__name");
            Elements prize = product.getElementsByClass("price");

            if (!names.isEmpty() && !prize.isEmpty()) {
                // Dodawanie danych do modelu tabeli
                tableModel.addRow(new Object[]{names.get(0).text(), prize.get(0).text()});
            }
        }

        // Ustawianie modelu tabeli w JTable
        jTable1.setModel(tableModel);
        
         // tworzenie pdf
            PDDocument document = new PDDocument();
            PDPage page = new PDPage();
            document.addPage(page);

            // tworzenie content
            PDPageContentStream contentStream = new PDPageContentStream(document, page);

            // headers
            contentStream.setFont(PDType1Font.HELVETICA, 12);
            contentStream.beginText();
            contentStream.newLineAtOffset(100, 750);
            contentStream.showText("Product Name");
            contentStream.newLineAtOffset(200, 0);
            contentStream.showText("Price");
            contentStream.endText();

            // dane produktow do pdf
            for (Element product : productsAnswear) {
                Elements names = product.getElementsByClass("ProductItem__productCardName__DCKIH");
                Elements prize = product.getElementsByClass("ProductItemPrice__priceSaleMinimal__+YZVp");

                if (!names.isEmpty() && !prize.isEmpty()) {
                    // szczegoly prod do PDF
                    contentStream.beginText();
                    contentStream.newLineAtOffset(100, 700); // 1 poz
                    contentStream.showText(names.get(0).text());
                    contentStream.newLineAtOffset(200, 0);
                    contentStream.showText(prize.get(0).text());
                    contentStream.endText();
                }
            }

            // zamkniecie
            contentStream.close();

            // zapis do pliku
            document.save("zadanie1.pdf");

            // zamkniecie
            document.close();

            System.out.println("PDF generated successfully!");
            
   
    } catch (IOException e) {
        throw new RuntimeException(e);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OKNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OKNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OKNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OKNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OKNO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
